DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(10) NOT NULL,
    document_number VARCHAR(20) NOT NULL,
    names VARCHAR(50) NOT NULL,
    surnames VARCHAR(50) NOT NULL,
    area VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    CONSTRAINT uk_employee_doc UNIQUE (document_type, document_number)
);

DROP TABLE IF EXISTS travels;

CREATE TABLE travels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS bills;

CREATE TABLE bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    start_date DATE NOT NULL,
    duration_days INT NOT NULL CHECK (duration_days > 0),
    end_date DATE NOT NULL,
    CONSTRAINT fk_travel FOREIGN KEY (travel_id) REFERENCES travels(id) ON DELETE CASCADE,
    CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);