DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(10) NOT NULL,
    document_number VARCHAR(20) NOT NULL,
    names VARCHAR(50) NOT NULL,
    surnames VARCHAR(50) NOT NULL,
    area VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    CONSTRAINT uk_employee_doc UNIQUE (document_type, document_number)
);

DROP TABLE IF EXISTS travels;

CREATE TABLE travels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination VARCHAR(100) NOT NULL
);